### ISSUE TITLE
[linux] sections fail: integer divide by zero 

### ISSUE THREAD

**Issue by olebole** [iraf/iraf-v216#63]
On linux (32 bit), many (but not all) operations with sections fail due to a divide-by-zero error:
```
ecl> imhead dev$pix
dev$pix[512,512][short]: m51  B  600s
ecl> imhead dev$pix[10:20,10:20]
dev$pix[10:20,10:20][11,11][short]: m51  B  600s
ecl> imcopy dev$pix im1
dev$pix -> im1
ecl> imcopy dev$pix[10:20,10:20] im2
dev$pix[10:20,10:20] -> im2
ERROR: integer divide by zero
```
On linux64, that works well.

**Comment by olebole** [comment]
Update here: This may have the cause that `evvexpr.x` finally does not get compiled:
```
xc -c -w [...] evvexpr.x [...]
[...]
evvexpr.x:
   evvexpr:
   evvfree:
   xvv_unop:
   xvv_binop:
   xvv_boolop:
   xvv_patmatch:
   xvv_newtype:
   xvv_quest:
   xvv_callfcn:
   xvv_startarglist:
   xvv_addarg:
   xvv_error1:
   xvv_error2:
   xvv_error:
   xvv_chtype:
   xvv_initop:
   xvv_makeop:
   xvv_freeop:
   xvv_loadsymbols:
   xvv_nulls:
   xvv_nulli:
   xvv_nulll:
   xvv_nullr:
   xvv_nulld:
   yyparse:
[...]
evvexpr.f:
   evvexr:
   evvfre:
   xvvunp:
   xvvbip:
   xvvbop:
   xvvpah:
   xvvnee:
   xvvqut:
   xvvcan:
Compiler error line 5369 of evvexpr.f: Too many statement labels.
Table limit now 801.
Try rerunning with the -Ns1602 option.

/home/oles/Projects/2015/upstream/iraf/iraf-v216//unix/hlib/f77.sh: line 209: evvexpr.c: No such file or directory
mv: cannot stat 'evvexpr.t': No such file or directory
sed: can't read evvexpr.c: No such file or directory
gcc: error: evvexpr.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
ar r /home/oles/Projects/2015/upstream/iraf/iraf-v216//lib/../bin/libsys.a cctoc.o chdeposit.o chfetch.o chrlwr.o chrupr.o clprintf.o clscan.o ctocc.o ctod.o ctoi.o ctol.o ctor.o ctotok.o ctowrd.o ctox.o dtcscl.
ar: evvexpr.o: No such file or directory
```
Earlier in the build, the same library already was built, with the correct call, and succeeding:
```
xc -c -w -/Nx512 -/Ns2048 evvexpr.x
evvexpr.x:
   evvexpr:
   evvfree:
   xvv_unop:
   xvv_binop:
   xvv_boolop:
   xvv_patmatch:
   xvv_newtype:
   xvv_quest:
   xvv_callfcn:
   xvv_startarglist:
   xvv_addarg:
   xvv_error1:
   xvv_error2:
[...]
evvexpr.f:
   evvexr:
   evvfre:
   xvvunp:
   xvvbip:
   xvvbop:
   xvvpah:
   xvvnee:
   xvvqut:
   xvvcan:
   xvvstt:
   xvvadg:
   xvver1:
[...]
ar r /home/oles/Projects/2015/upstream/iraf/iraf-v216/lib/../bin/libsys.a cctoc.o chdeposit.o [...] evvexpr.o [...] xvvgettok.o xtoc.o
```
I have no idea why it is built twice, and why at the second time the wrong flags are used.
